<a href="https://colab.research.google.com/github/ANITHAKISHORE/EDA/blob/main/Copy_of_numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5]) 

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr[0][0])
print(arr.shape)

[[1 2 3]
 [4 5 6]]
1
(2, 3)


In [ ]:
x = np.where(arr == 4)

print(x)

(array([1]), array([0]))


In [ ]:
from numpy import random

x = random.randint(1,10)

print(x)

3


In [ ]:
from numpy import random

x = random.rand()

print(x)

0.05740635877951161


In [ ]:
from numpy import random

x = random.rand()

print(x)

0.2400688815464861


In [ ]:
x = random.normal()

print(x)

-0.1650338786866602


In [ ]:
x = random.binomial(n=10, p=0.5, size=10)

print(x)

[4 4 4 5 7 4 7 4 8 6]


In [ ]:
x = random.uniform()

print(x)

0.8654902380156719


In [ ]:
x = random.exponential(scale=2)

print(x)

0.12817435123369342


In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [ ]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [ ]:
arr = np.array([3, 7, 9, 8, 2, 33])
print(np.log2(arr))

[1.5849625  2.80735492 3.169925   3.         1.         5.04439412]
